Algoritmo "MaiorMenor"

Var
// Seção de Declarações das variáveis 
n1,n2 : inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Leia o primeiro número:")
   leia(n1)
   escreval("Leia o segundo número:")
   leia(n2)
   
   se (n1 > n2) entao
      escreva("O primeiro número é maior que o segundo.")
   senao
      escreva("O segundo número é maior que o primeiro.")
   fimse
   

Fimalgoritmo